---
abstract: 'assemble/disassemble network packets at the protocol level'
author:
  - 'Tim Potter <tpot@samba.org>'
  - 'Stephanie Wehner <atrak@itsx.com>'
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Errno: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NetPacket
provides:
  NetPacket:
    file: lib/NetPacket.pm
    version: v1.4.0
  NetPacket::ARP:
    file: lib/NetPacket/ARP.pm
    version: v1.4.0
  NetPacket::Ethernet:
    file: lib/NetPacket/Ethernet.pm
    version: v1.4.0
  NetPacket::ICMP:
    file: lib/NetPacket/ICMP.pm
    version: v1.4.0
  NetPacket::IGMP:
    file: lib/NetPacket/IGMP.pm
    version: v1.4.0
  NetPacket::IP:
    file: lib/NetPacket/IP.pm
    version: v1.4.0
  NetPacket::TCP:
    file: lib/NetPacket/TCP.pm
    version: v1.4.0
  NetPacket::UDP:
    file: lib/NetPacket/UDP.pm
    version: v1.4.0
  NetPacket::USBMon:
    file: lib/NetPacket/USBMon.pm
    version: v1.4.0
requires:
  constant: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=NetPacket
  homepage: http://search.cpan.org/dist/NetPacket/
  repository: https://github.com/yanick/netpacket.git
version: 1.4.0
x_authority: cpan:YANICK
x_contributors:
  - 'Ben Magistro <koncept1@gmail.com>'
  - 'Lubomir Rintel <lkundrak@v3.sk>'
  - 'Robin Lee <cheeselee@fedoraproject.org>'
  - 'Stan Schwertly <stan@linode.com>'
  - 'Stephanie Wehner <atrak@cpan.org>'
  - 'Tim Potter <timpotter@cpan.org>'
